# Generated by Django 2.1.4 on 2019-01-20 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_proto', '0002_adminuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminuser',
            old_name='admin',
            new_name='user',
        ),
    ]
